### ISSUE TITLE
Found Gradle Issue while adding new dependencies

### ISSUE THREAD

**Issue by imafzalakram** [Starcommander/StreamRadio#10]
I am facing Gradle issues while adding dependencies for other github libraries. It throughs runTime exception. Gradle build system fails when I add any external libraries.

**Comment by Starcommander** [comment]
Hello @imafzalakram 
Can you add more information to this issue?
What are the "github libraries" that you want to add to the gradle project?
And what exactly is the issue? (Can you post the exception)

**Comment by Starcommander** [comment]
As this is a general use case regarding gradle, I will close this Issue.
