### ISSUE TITLE
App stops after some minutes with Battery optimization (since Android 6)

### ISSUE THREAD

**Issue by alltagshack** [Starcommander/StreamRadio#5]
On my Android 8.1 (LineageOS) device the webstream stops, if it switch to a default deep-sleep mode. If I disable "Battery optimization" for WebRadio, stream/WebRadio did not stop the player.

Because the "Battery optimization" settings dialog is hard to find on Android, WebRadio should add a "Shortcut" to its options menu. This make user easier to deactivate the optimization like this:

![webradio_akku_not_opt](https://user-images.githubusercontent.com/12084008/54882770-b52c1180-4e5d-11e9-86b3-da2c3076ccf0.jpg)

**Comment by Starcommander** [comment]
Paradoxically on my Phone there is no problem, when phone is in sleep mode.
(LineageOS 7.1.2)
Technically there are some impressions regarding battery optimization:
https://stackoverflow.com/questions/39256501/check-if-battery-optimization-is-enabled-or-not-for-an-app

**Comment by alltagshack** [comment]
Hi. Nice link. I think, it is not device independent, if battery optimization stops all network traffic. I had similar issue in a RSS Feed Reader App, where alarm entries never waked up on some devices.

**Comment by alltagshack** [comment]
fixed in https://github.com/Starcommander/StreamRadio/commit/311921bb6c931aaf743a73955ceb002f2ad81062
