### ISSUE TITLE
Cannot build with api 16

### ISSUE THREAD

**Issue by Starcommander** [Starcommander/StreamRadio#6]
Building the project (via gradle) results into lint-errors, because try-with-resources is not supported.
So I had to change the min sdk to 19.

**Error:**
`/home/ppp/delete_StreamRadio/StreamRadio_ci/StreamRadio_testbuild/app/src/main/java/starcom/snd/array/ChannelList.java:172: Error: Try-with-resources requires API level 19 (current min is 16) [NewApi]
      try(FileInputStream is = activity.openFileInput(channelFile);`

**Changes:**
```
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -5,7 +5,7 @@ android {
 
     defaultConfig {
         applicationId "starcom.snd"
-        minSdkVersion 16
+        minSdkVersion 19
         targetSdkVersion 26
     }

```

**Comment by alltagshack** [comment]
that is bad. strange, that it build on my system.

**Comment by Starcommander** [comment]
Maybe disabled **lint** somehow?
Do we need sdk version 16?

**Comment by Starcommander** [comment]
An other way is to change the try block to old style.

**Comment by alltagshack** [comment]
I think many old phones still have Android 4.1 and not 4.4

changing the try in another/old way would be my favourit solution. :-D

**Comment by Starcommander** [comment]
4.1 is really old ;)
But in my opinion both solutions are acceptable.

**Comment by alltagshack** [comment]
we do not need 16, but the update reach more devices.

I am sorry, but I did not really know how hard it is to change the "try" code.~~I would use a string array with "shared Preferences" instead of file-access as channel storage.~~

**Comment by Starcommander** [comment]
It is not very hard.
Example old style:

```
InputStream in;
try
{
  in = new .......;
  // read data
}
catch (XXXException e)
{
  // do anything
}
finally
{
  if (in != null)
  {
    try { in.close(); } catch (Exception e) {}
  }
}
```
This will ensure, that the stream is closed in any case.
But the new style "try-with-resources" looks more clear.

**Comment by alltagshack** [comment]
hm. of course this is more complex than changing 16 to 19. Maybe I can catch you with the argument, that it is more a political desission making App compatible to old systems. A bit wired example: I have to move my Iphone4 to trash, because I did not get old App versions for my old system. Additionally I leave "google play" because they force developing for "Nougat?"

many times I develop for target SDK 22, because you see every permission for the App before installation. I love this feature and since 23 it got lost :-(

I do not think, that my preferences in that point are mainstream :-/ It is your project - feel free to decide :-D

**Comment by Starcommander** [comment]
Ok, lets make it compatible with 16.
Files to change: ChannelList.java and Resources.java
Do you want to make the changes?

**Comment by alltagshack** [comment]
I would like to make these changes, but my buildsystem seems to ignoring that trouble :-(

**Comment by alltagshack** [comment]
it is similar to the "energy save issue"... it will be better, that I found a solution, because I got the trouble ;-)

**Comment by Starcommander** [comment]
For building the project I just execute "gradlew build" from command line on my linux system.
This also executes the lint-analysis, that is failing.
Maybe your build system (IntelliJ?) does not execute the lint-analysis, so your build does not fail.
https://en.wikipedia.org/wiki/Lint_(software)

**Comment by alltagshack** [comment]
ok, I will try :-D

**Comment by Starcommander** [comment]
Basically you can also just modify the source.
Finally building the app will be done on FDroid server.
And I can make the lint-analysis-test before releasing the app.

**Comment by alltagshack** [comment]
fixed in https://github.com/Starcommander/StreamRadio/commit/311921bb6c931aaf743a73955ceb002f2ad81062
