### ISSUE TITLE
The reading stops every two or three minutes

### ISSUE THREAD

**Issue by Rebecca-du-58** [Starcommander/StreamRadio#8]
I really don't know what to do about this. The player works when I choose my favorite web radio. Then after a few minutes, it stops. I have to press play again. It goes on and on. 
However I tried to keep the screen awake but it is still the same. There is no battery restriction. If I read the web radio from the browser, there is no interruption. So it comes from the app.
What should I do about it?
I have a Redmi 6A. With Android 9.

**Comment by Starcommander** [comment]
Do you have the web-url to your favourite web-radio?
Do you have the same problems with pre-configured radio channels?

**Comment by Rebecca-du-58** [comment]
The link is:
http://play.organlive.com:7002/320
Funnily I am presently using my phone while listing to Positively Baroque and it happened again. It just disappears from the notification bar and I need to go back to the app _ as I was doing something else _ and press play to go back to my listening.
Maybe at some point, Android kills the app? I gave all the privileges to this app but what else can I do?
I'm presently listening to one of the included webradios...

**Comment by Rebecca-du-58** [comment]
Actually this problem doesn't occur with an included webradio. Very strange...

**Comment by Rebecca-du-58** [comment]
Well it works perfectly with another of my webradios, as well as with the included ones. Funny!...

**Comment by Rebecca-du-58** [comment]
With that one, it stutters:
http://play2.organlive.com:7000/350
It's another station. Not the one I mentioned at first.
Any idea why?

**Comment by Starcommander** [comment]
_I was able to reproduce the issue with stopping player.
Unfortunately it has to do with the native player of android.
Seems the stream-data is sometimes corrupted, and therefore breaks playing data.
Log-output:_
12-06 12:37:30.418  1105 16163 E NuCachedSource2: source returned error -1, 10 retries left
**12-06 12:37:57.235  1105 16163 E NuCachedSource2: source returned error -1010, 0 retries left**
12-06 12:37:57.277   847 16280 E ACDB-LOADER: [acdb_loader_store_get_audio_cal] Error: ACDB get returned = -8 length 0
12-06 12:37:57.277   847 16280 D offload_effect_pbe: pbe_load_config ret = -8, len = 0
12-06 12:37:57.279   847  2746 I offload_effect_bb: bassboost_set_device: ctxt 0xf467b698, disabled based on device
12-06 12:37:57.282   847 16280 I offload_effect_virtualizer: virtualizer_set_device: ctxt 0xf3b1fa80, disabled based on device
12-06 12:37:57.287   847 16280 D offload_effect_bass: bass_set_parameter ignore set strength, index 1
12-06 12:37:57.342   847 17080 D msm8974_platform: platform_set_channel_map mixer_ctl_name:Playback Channel Map0
12-06 12:37:57.343   847 17080 D msm8974_platform: platform_set_channel_map: set mapping(1 2 0 0 0 0 0 0) for channel:2
12-06 12:37:57.344   847 17080 D audio_hw_primary: start_output_stream: exit
12-06 12:37:57.444   885  1649 D AudioFlinger: mixer(0x783ef92f80) throttle end: throttle time(38)
12-06 12:37:57.446  1507  1507 V SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
12-06 12:37:57.523   845   981 W qti_sensors_hal: processReportInd: lux: 194, ch0: 0, ch1: 6514, pData: 119, pOffset: 26
**12-06 12:37:58.015  1105 16169 E NuPlayerDecoder: Stream error for [OMX.google.mp3.decoder] (err=-2147483648), EOS successfully queued**
12-06 12:37:58.015  1105 16159 E NuPlayer: received error(0x80000000) from audio decoder, flushing(0), now shutting down
12-06 12:37:58.015  1105 16169 E NuPlayerDecoder: Stream error for [OMX.google.mp3.decoder] (err=-2147483648), EOS successfully queued
12-06 12:37:58.015 15925 16032 E MediaPlayerNative: error (1, -2147483648)
12-06 12:37:58.016 15925 15925 E MediaPlayer: Error (1,-2147483648)
12-06 12:37:58.016  1105 16159 E NuPlayer: received error(0x80000000) from audio decoder, flushing(2), now shutting down
12-06 12:37:58.016 15925 16032 E MediaPlayerNative: error (1, -2147483648)
12-06 12:37:58.017 15925 15925 I WebStreamPlayer: Stop MediaPlayer.
12-06 12:37:58.017 15925 15925 I WebStreamPlayer: Set to new State: Stopped
12-06 12:37:58.032 15925 15925 E MediaPlayerNative: pause called in state 0, mPlayer(0x77846cd5c0)
12-06 12:37:58.032 15925 15925 E MediaPlayerNative: error (-38, 0)
12-06 12:37:58.032 15925 15925 E MediaPlayerNative: stop called in state 0, mPlayer(0x77846cd5c0)
12-06 12:37:58.032 15925 15925 E MediaPlayerNative: error (-38, 0)

**Comment by Starcommander** [comment]
Currently I was able to play 1/2h without any interruption.
I will retry later.

The play2-link stutters on my mobile and also on linux mplayer.
There is no error message.
So I think, it plays the audio data as provided.

**Comment by Starcommander** [comment]
With the new option you can select to continue a broken stream.
The stream will stop, but start again automatically.
This is a workaround and should fix the issue as far as possible.
Available in next release.
